name: SonarCloud
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - run: npm build
      - run: npm test
      - run: ls ${{github.workspace}}/src/frontend/coverage
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Analyze with SonarCloud
        run: ls ${{github.workspace}}/src/frontend/coverage
      - run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{secrets.SONAR_KEY}} -Dsonar.organization=${{secrets.SONAR_ORG}} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN}} -Dsonar.sources=./src/main -Dsonar.tests=src/main/resources/public -Dsonar.test.inclusions=**/*.test.js -Dsonar.coverage.jacoco.xmlReportPaths=${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco -Dsonar.javascript.lcov.reportPaths=${{github.workspace}}/src/frontend/coverage/lcov.info:lcov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}